
export const PROCUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PROCUCT_LIST_SUCCESS = 'PROCUCT_LIST_SUCCESS';
export const PROCUCT_LIST_FAIL = 'PROCUCT_LIST_FAIL';

export const PROCUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PROCUCT_DETAILS_SUCCESS = 'PROCUCT_DETAILS_SUCCESS';
export const PROCUCT_DETAILS_FAIL = 'PROCUCT_DETAILS_FAIL';
